### ISSUE TITLE
高亮样式缺少 hljs 类

### ISSUE THREAD

**Issue by xubaifuCode** [mengdu/vue-dotmd-loader#13]
https://github.com/mengdu/vue-dotmd-loader/blob/e619d53b2af0ac55014004f8305c18fc5cbea51b/src/index.js#L63

如果使用其他 hilightjs 的主题样式会导致没有背景色等效果

**Comment by mengdu** [comment]
@xubaifuCode 我没提供有自定义高亮代码的配置，你是怎么用的，代码块是不是没被高亮库解析？样式用了么

**Comment by xubaifuCode** [comment]
> @xubaifuCode 我没提供有自定义高亮代码的配置，你是怎么用的，代码块是不是没被高亮库解析？样式用了么

我没有引入你在文档里提及的样式，引入的是：

`import 'highlight.js/styles/atom-one-dark.css'`

代码的高亮样式是符合预期的，但缺少的外围的背景色，排查后发现只是少了 `hljs` 这个类名。理论上引入其他的样式可以复现这个问题。

![image](https://user-images.githubusercontent.com/14217592/102568463-7dc7c300-411e-11eb-826c-023db1a7f48e.png)

当我复制了你内置的高亮部分代码并自己加上 hljs 样式后效果就符合预期了

**Comment by mengdu** [comment]
如果你要跟案例一样的样式是需要使用以下样式文件的

```js
import 'github-markdown-css/github-markdown.css' // markdown 样式
import 'highlight.js/styles/color-brewer.css' // 代码高亮
import 'vue-dotmd-loader/src/docs.css' // 文档页面样式
```

**Comment by xubaifuCode** [comment]
> 如果你要跟案例一样的样式是需要使用以下样式文件的
> 
> ```js
> import 'github-markdown-css/github-markdown.css' // markdown 样式
> import 'highlight.js/styles/color-brewer.css' // 代码高亮
> import 'vue-dotmd-loader/src/docs.css' // 文档页面样式
> ```

可能我没表达清楚，这边是正好想自定义代码块的样式，才引入的其他样式，然后顺道发现了 `<pre class="language${lang ? ' language-' + lang : ''}" data-lang="${lang}">` 缺少 `hljs` 这个问题。

只需要改成`<pre class="hljs language${lang ? ' language-' + lang : ''}" data-lang="${lang}">` 即可。

**Comment by mengdu** [comment]
已经增加上去了
