### ISSUE TITLE
如何在md中编辑组件

### ISSUE THREAD

**Issue by YaleWan** [mengdu/vue-dotmd-loader#3]
![image](https://user-images.githubusercontent.com/42661750/76326249-589e5c80-6323-11ea-9067-629446b362a2.png)
我现在第一种情况是可以的，第二种情况不可以，我如何直接在md中编写组件，然后直接变成demo-code的形式？

**Comment by mengdu** [comment]
这样写：

![image](https://user-images.githubusercontent.com/11366654/76327008-686a7080-6324-11ea-915a-3f32d443adf0.png)

这里有个 [说明文档](https://github.com/mengdu/vue-dotmd-loader/blob/master/examples/docs.md) ，可以看源md文件里的写法。

**Comment by YaleWan** [comment]
![image](https://user-images.githubusercontent.com/42661750/76376177-a0a09c00-6382-11ea-90a2-0ee6a365c8cb.png)
![image](https://user-images.githubusercontent.com/42661750/76376209-b910b680-6382-11ea-9ef5-9b6074a3cf91.png)
可是最终的结果确实这样子的
![image](https://user-images.githubusercontent.com/42661750/76376233-c7f76900-6382-11ea-9bfa-8eef5dcd8ff8.png)
