### ISSUE TITLE
md文件中，要显示目录怎么添加呀？

### ISSUE THREAD

**Issue by pcloth** [mengdu/vue-dotmd-loader#39]
推荐直接将md的各级级标题设置成为导航栏目录菜单和锚点
比如
`
# 栏目1
## 栏目1子菜单
# 栏目2
`

点击菜单标题就可以跳转到指定的标题锚点

**Comment by mengdu** [comment]
你可以配置插件里init里增加markdown-it的插件就可以了
可以用 https://www.npmjs.com/package/markdown-it-table-of-contents 这个插件
